### ISSUE TITLE
[Feature] Font Settings

### ISSUE THREAD

**Issue by haukefrahmann** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#1]
it would be nice, to have the font settings like in the "textbox" availlable

**Comment by saif-ellafi** [comment]
Yes that would be cool or pull from the "Default Drawing Configuration" which would be an option "more integrated with Foundry". Although not necessary the most convenient.

![image](https://user-images.githubusercontent.com/27952699/114872684-d96b3a00-9dfa-11eb-8ac6-1a1bfe4fc90e.png)

**Comment by Galdormin** [comment]
I will handle this in the next release. I guess default setting will be a good idea to handle font, background color and text color.
