### ISSUE TITLE
"You dragged the aspect outside the canvas" in Firefox

### ISSUE THREAD

**Issue by erikblanchard** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#15]
No matter where the aspect is dragged, this message will pop up and the text box will not be placed in the scene. This is using the Fate Core Official v 4.3.21, Foundry VTT v9 build 255.

**Comment by Galdormin** [comment]
I cannot manage to replicate on my side. I'll need more information about it.

Have you tried with all other module disabled (except for FateAspectTracker and SortableJS) ?

**Comment by erikblanchard** [comment]
Not sure what fixed it but it seems to be fine now. Sorry for the false alarm.
