### ISSUE TITLE
Module still maintained?

### ISSUE THREAD

**Issue by MSAbaddon** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#16]
Hi there,
quick question - is the module still maintained? I did some coding changes for V10 compatibility - maybe you can give me permissions to upload a branch and create a merge request?

**Comment by Galdormin** [comment]
The module is still maintained, but I won't add new features. I was planning to update it to V10, but if you already did it I will use your update.

I've created a branch, you should be able to push on it.

**Comment by MSAbaddon** [comment]
Thanks for the reply - I created a pull request to your branch. If I happen to add new functionality to the module - would you add it to the module?

**Comment by Galdormin** [comment]
Thank you for the pull request. 

If you want to add some features and if they fit what I have in mind (mainly: easy to use and system agnostic) I will be happy to add them to the module.

If you want to exchange in more depth about the module or if you want faster replies, don't hesitate to contact me on discord (Galdormin#6561).

**Comment by MSAbaddon** [comment]
Ok, I'll check if some of the additions I have in mind are system agnostic. If I find some I'll send them as pull requests :-)
