### ISSUE TITLE
[Feature] Calender/Weather

### ISSUE THREAD

**Issue by haukefrahmann** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#2]
it would be nice if the tracker could "grap" the information from calender/weather

I use in little very simple macro like this: document.getElementById("calendar-weather-precip").innerHTML;

**Comment by Galdormin** [comment]
I will handle this through a macro because I want to keep the UI as minimalist as possible.
In the next release (today or tomorrow), there will be a macro folder with the **Weather to Aspect** macro in it.
