### ISSUE TITLE
Support for version 11

### ISSUE THREAD

**Issue by thadrine** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#20]
Module validation error on installing the mod.

**Comment by Plenett** [comment]
Hello, 
The module is working for V11 but the installation is not.
I'm not sure what the error is, and I don't have much time to investigate the problem. 
In the mean time, you can still download the Zip file and install it manually.

**Comment by r-valyar** [comment]
The module indeed cannot be installed via the Add-On user interface.

![image](https://github.com/Galdormin/FoundryVTT-Fate-Aspect-Tracker/assets/63558984/9d35df89-6723-459f-ac77-7cf99ef1e6aa)

**Comment by theczarek** [comment]
Module cannot be instaled due to files "module.jason" been removed form all github releases.

**Comment by RinVindor** [comment]
Came here to request this same update lol

**Comment by r-valyar** [comment]
@Galdormin would you let us know if the module will get an update or we should look for a fork?

**Comment by Galdormin** [comment]
Hi, sorry for the delay. I solve the manifest problem and the module is working, but some other problems remains (see issue#21). I don't have time to investigate the problem right now.

To install the module you need to:
1. Go into the module folder (Data/Modules) and remove the old version of `fate-aspect-tracker`
2. Download manually the module.zip from the last version (v1.2.1 https://github.com/Galdormin/FoundryVTT-Fate-Aspect-Tracker/releases/tag/v1.2.1)
3. Create a folder with the name `fate-aspect-tracker`
4. Extract module.zip inside it 

The module should work.

If you have some time, feel free to fork the repo and ask for a merge request (I will have enough time to accept a merge request)

**Comment by VelniasQ** [comment]
After the last update the new issue is:
```
Error: Cannot read properties of null (reading 'protected')
```

**Comment by AbelinLamarisi** [comment]
Thank you @Galdormin,

I reinstalled v1.2.1, but I still have an issue with it:
<img width="597" alt="image" src="https://github.com/Galdormin/FoundryVTT-Fate-Aspect-Tracker/assets/2045201/e2de8909-1bdd-41f2-9350-25b4718a1917">
![image](https://github.com/Galdormin/FoundryVTT-Fate-Aspect-Tracker/assets/2045201/820deb14-d294-4c07-92b2-815a6fd37fcc)

**Comment by Galdormin** [comment]
The module is working correctly now, you can download it as usual.

**Comment by AbelinLamarisi** [comment]
Thank you 🙇,

I've reinstalled it and I'm still having problems with the previous image.

**Comment by Galdormin** [comment]
@VelniasQ Macros are broken for now
