### ISSUE TITLE
Problem with module automatic installation

### ISSUE THREAD

**Issue by Galdormin** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#21]
The module is working properly for V11, but the automatic installation is not working. The error is thrown by `setup.js` and the files are not extracted properly from the module.zip.

![image](https://github.com/Galdormin/FoundryVTT-Fate-Aspect-Tracker/assets/76685550/58fd0af2-01b6-4d4b-ae44-f96426940e8b)

To replicate:
1. Uninstall `fate-aspect-tracker`
2. Install the module from the *Add-on Modules* tab

**Comment by Andyvec** [comment]
The same is happening to me.
I'm installing it for the first time, using Foundry v11 build 307 (latest stable at the time of writing this), and is giving me the same error message reported here. The installation failed after that.

**Comment by Galdormin** [comment]
To install the module you need to:

1. Go into the module folder (Data/Modules) and remove the old version of `fate-aspect-tracker` (delete the folder)
2. Download manually the `module.zip` from the last version (v1.2.1 https://github.com/Galdormin/FoundryVTT-Fate-Aspect-Tracker/releases/tag/v1.2.1)
3. Create a folder with the name `fate-aspect-tracker`
4. Extract `module.zip` inside it

**Comment by Andyvec** [comment]
Hi @Galdormin,
Thanks for sharing the workaround steps.
Will I be able to update and delete the plugin if I install it that way?

**Comment by SalieriC** [comment]
That won't do it because the releases zip lacks the files necessary. Foundry immediately complains about `modules/fate-aspect-tracker.js` being missing.

**Comment by Galdormin** [comment]
Thank you @SalieriC, my deployment script was broken (zip -R instead of zip -r). The module is working correctly now.
