### ISSUE TITLE
Unable to activate the module due to hidden dependencies

### ISSUE THREAD

**Issue by Andyvec** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#22]
Hi,

After the last fix update, I was able to install this module through the Foundry automation, but I'm unable to activate the module in any of my existing worlds due to "issues with the required dependencies".
The checkbox to activate that module in my world is gray out, and there is no related message in the console, neither a hint on which is the required dependency.

![image](https://github.com/Galdormin/FoundryVTT-Fate-Aspect-Tracker/assets/625233/d14a84f7-cc8a-42dd-83ec-6b5a09fa3137)

**Comment by RinVindor** [comment]
Yeah I can't even install it anymore as I tried to uninstall it.

![image](https://github.com/Galdormin/FoundryVTT-Fate-Aspect-Tracker/assets/12647469/55a4492f-895d-4d18-a5c7-39421409f887)

However searching for it in Foundry wouldn't pull it up I had to find it via a Google Search and use the manifest link.

Even with that installed Fate Aspect Tracker doesn't even show up in my modules despite being installed.

**Comment by Orphansmith** [comment]
I also have this issue. Is this module dead?

**Comment by Plenett** [comment]
The dependency `_sortable.js` has not been updated for the major changes of V11. I will try to add the dependency locally.

**Comment by Plenett** [comment]
Version `v1.3.0` should fix the issue.
