### ISSUE TITLE
[BUG] Textsize

### ISSUE THREAD

**Issue by haukefrahmann** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#3]
the textsize ist everytime 17 whatever is in the defaults

**Comment by Galdormin** [comment]
This isn't a bug, the textsize depends on the canvas size. The aspect textbox size (font size, box width and heigth) are relative to the canvas size.

I may make a setting to change the relative value of textbox size but it will remain relative for every textbox to have the same size relatively to the canvas.
