### ISSUE TITLE
[BUG] out of canvas

### ISSUE THREAD

**Issue by haukefrahmann** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#4]
after deleting an aspect I can not put any other aspects on the canvas

always the message "you dragged out of the canvas"

this happens since the v0.3

**Comment by Galdormin** [comment]
This error is thrown when you want to dragg an aspect on the canvas but you dragged it outside the canvas.

I can not manage to replicate the bug on my side... 
Can you provide me the `_aspect_tracker` journal entry when you manage to replicate the bug ?

**Comment by haukefrahmann** [comment]
veeery strange ... is only in one screne this problem....

[{"description":"Test1","tag":"Test2","color":"#742525","invoke":2,"drawings":[]}]

**Comment by Galdormin** [comment]
Try the following: 
1. Delete the journal `_aspect_tracker`.
2. Restart the game.
3. Try the operation that gave you the bug.

Did you obtain something different ?

**Comment by haukefrahmann** [comment]
that's it

ahh... I open the journal ... just to see... I might have saved it .. so it got broken

**Comment by Galdormin** [comment]
Ok good to know. I will find a way to hide the journal to avoid this kind of problem.
