### ISSUE TITLE
[Feature] Change the color of the dragged aspects 

### ISSUE THREAD

**Issue by smoothingplane** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#6]
After dragging the appearance on the canvas, the text becomes white without taking the color given by the module, moreover it remains constantly selected (with the border and the white background) making the visualization not very easy.
![image](https://user-images.githubusercontent.com/43862671/114996109-cdd14f00-9e9e-11eb-9d89-3807bfcb3ef6.png)

**Comment by Galdormin** [comment]
The text color, background color, line color are based on the default drawing settings. Only the box size and font size cannot be change through the default settings, they are computed based on the canvas size.
![screenshot](https://user-images.githubusercontent.com/76685550/115008886-f6ac1100-9eab-11eb-8725-10e0df8f69a9.png)

In the future, I will find a way to display the aspect color and the tag on the text box.

**Comment by saif-ellafi** [comment]
Another idea to consider is to use the colour of the aspect in the manager itself!. Just a random thought.

**Comment by saif-ellafi** [comment]
So you wouldn't have to add a color option but directly use the one of the aspect itself :)
